# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Wed, 18 Mar 2015 22:00:20 +0000
*               @ALL          0
*               @user         8
