<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: lucazz
 * Date: Wed, 18 Mar 2015 16:32:21 -0700
 */

$conf['title'] = '<br>IFCE<br>Documentação Oficial da Infraestrutura';
$conf['template'] = 'codowik-master';
$conf['license'] = '0';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['htmlok'] = 1;
$conf['phpok'] = 1;

// end auto-generated content
